/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as protectedDashboardImport } from './routes/(protected)/_dashboard'
import { Route as protectedOnboardingIndexImport } from './routes/(protected)/onboarding/index'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'
import { Route as protectedDashboardQuestionnaireIndexImport } from './routes/(protected)/_dashboard/questionnaire/index'
import { Route as protectedDashboardJournalIndexImport } from './routes/(protected)/_dashboard/journal/index'
import { Route as protectedDashboardHomeIndexImport } from './routes/(protected)/_dashboard/home/index'
import { Route as protectedDashboardChatSessionIdImport } from './routes/(protected)/_dashboard/chat/$sessionId'

// Create Virtual Routes

const protectedImport = createFileRoute('/(protected)')()

// Create/Update Routes

const protectedRoute = protectedImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const protectedDashboardRoute = protectedDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => protectedRoute,
} as any)

const protectedOnboardingIndexRoute = protectedOnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => protectedRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const protectedDashboardQuestionnaireIndexRoute =
  protectedDashboardQuestionnaireIndexImport.update({
    id: '/questionnaire/',
    path: '/questionnaire/',
    getParentRoute: () => protectedDashboardRoute,
  } as any)

const protectedDashboardJournalIndexRoute =
  protectedDashboardJournalIndexImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => protectedDashboardRoute,
  } as any)

const protectedDashboardHomeIndexRoute =
  protectedDashboardHomeIndexImport.update({
    id: '/home/',
    path: '/home/',
    getParentRoute: () => protectedDashboardRoute,
  } as any)

const protectedDashboardChatSessionIdRoute =
  protectedDashboardChatSessionIdImport.update({
    id: '/chat/$sessionId',
    path: '/chat/$sessionId',
    getParentRoute: () => protectedDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(protected)': {
      id: '/(protected)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/_dashboard': {
      id: '/(protected)/_dashboard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedDashboardImport
      parentRoute: typeof protectedRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/onboarding/': {
      id: '/(protected)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof protectedOnboardingIndexImport
      parentRoute: typeof protectedImport
    }
    '/(protected)/_dashboard/chat/$sessionId': {
      id: '/(protected)/_dashboard/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof protectedDashboardChatSessionIdImport
      parentRoute: typeof protectedDashboardImport
    }
    '/(protected)/_dashboard/home/': {
      id: '/(protected)/_dashboard/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof protectedDashboardHomeIndexImport
      parentRoute: typeof protectedDashboardImport
    }
    '/(protected)/_dashboard/journal/': {
      id: '/(protected)/_dashboard/journal/'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof protectedDashboardJournalIndexImport
      parentRoute: typeof protectedDashboardImport
    }
    '/(protected)/_dashboard/questionnaire/': {
      id: '/(protected)/_dashboard/questionnaire/'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof protectedDashboardQuestionnaireIndexImport
      parentRoute: typeof protectedDashboardImport
    }
  }
}

// Create and export the route tree

interface protectedDashboardRouteChildren {
  protectedDashboardChatSessionIdRoute: typeof protectedDashboardChatSessionIdRoute
  protectedDashboardHomeIndexRoute: typeof protectedDashboardHomeIndexRoute
  protectedDashboardJournalIndexRoute: typeof protectedDashboardJournalIndexRoute
  protectedDashboardQuestionnaireIndexRoute: typeof protectedDashboardQuestionnaireIndexRoute
}

const protectedDashboardRouteChildren: protectedDashboardRouteChildren = {
  protectedDashboardChatSessionIdRoute: protectedDashboardChatSessionIdRoute,
  protectedDashboardHomeIndexRoute: protectedDashboardHomeIndexRoute,
  protectedDashboardJournalIndexRoute: protectedDashboardJournalIndexRoute,
  protectedDashboardQuestionnaireIndexRoute:
    protectedDashboardQuestionnaireIndexRoute,
}

const protectedDashboardRouteWithChildren =
  protectedDashboardRoute._addFileChildren(protectedDashboardRouteChildren)

interface protectedRouteChildren {
  protectedDashboardRoute: typeof protectedDashboardRouteWithChildren
  protectedOnboardingIndexRoute: typeof protectedOnboardingIndexRoute
}

const protectedRouteChildren: protectedRouteChildren = {
  protectedDashboardRoute: protectedDashboardRouteWithChildren,
  protectedOnboardingIndexRoute: protectedOnboardingIndexRoute,
}

const protectedRouteWithChildren = protectedRoute._addFileChildren(
  protectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof protectedDashboardRouteWithChildren
  '/login': typeof authLoginIndexRoute
  '/onboarding': typeof protectedOnboardingIndexRoute
  '/chat/$sessionId': typeof protectedDashboardChatSessionIdRoute
  '/home': typeof protectedDashboardHomeIndexRoute
  '/journal': typeof protectedDashboardJournalIndexRoute
  '/questionnaire': typeof protectedDashboardQuestionnaireIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof protectedDashboardRouteWithChildren
  '/login': typeof authLoginIndexRoute
  '/onboarding': typeof protectedOnboardingIndexRoute
  '/chat/$sessionId': typeof protectedDashboardChatSessionIdRoute
  '/home': typeof protectedDashboardHomeIndexRoute
  '/journal': typeof protectedDashboardJournalIndexRoute
  '/questionnaire': typeof protectedDashboardQuestionnaireIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteWithChildren
  '/(protected)/_dashboard': typeof protectedDashboardRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(protected)/onboarding/': typeof protectedOnboardingIndexRoute
  '/(protected)/_dashboard/chat/$sessionId': typeof protectedDashboardChatSessionIdRoute
  '/(protected)/_dashboard/home/': typeof protectedDashboardHomeIndexRoute
  '/(protected)/_dashboard/journal/': typeof protectedDashboardJournalIndexRoute
  '/(protected)/_dashboard/questionnaire/': typeof protectedDashboardQuestionnaireIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/chat/$sessionId'
    | '/home'
    | '/journal'
    | '/questionnaire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/chat/$sessionId'
    | '/home'
    | '/journal'
    | '/questionnaire'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(protected)/_dashboard'
    | '/(auth)/login/'
    | '/(protected)/onboarding/'
    | '/(protected)/_dashboard/chat/$sessionId'
    | '/(protected)/_dashboard/home/'
    | '/(protected)/_dashboard/journal/'
    | '/(protected)/_dashboard/questionnaire/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRoute: typeof protectedRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRoute: protectedRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(protected)",
        "/(auth)/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(protected)": {
      "filePath": "(protected)",
      "children": [
        "/(protected)/_dashboard",
        "/(protected)/onboarding/"
      ]
    },
    "/(protected)/_dashboard": {
      "filePath": "(protected)/_dashboard.tsx",
      "parent": "/(protected)",
      "children": [
        "/(protected)/_dashboard/chat/$sessionId",
        "/(protected)/_dashboard/home/",
        "/(protected)/_dashboard/journal/",
        "/(protected)/_dashboard/questionnaire/"
      ]
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/(protected)/onboarding/": {
      "filePath": "(protected)/onboarding/index.tsx",
      "parent": "/(protected)"
    },
    "/(protected)/_dashboard/chat/$sessionId": {
      "filePath": "(protected)/_dashboard/chat/$sessionId.tsx",
      "parent": "/(protected)/_dashboard"
    },
    "/(protected)/_dashboard/home/": {
      "filePath": "(protected)/_dashboard/home/index.tsx",
      "parent": "/(protected)/_dashboard"
    },
    "/(protected)/_dashboard/journal/": {
      "filePath": "(protected)/_dashboard/journal/index.tsx",
      "parent": "/(protected)/_dashboard"
    },
    "/(protected)/_dashboard/questionnaire/": {
      "filePath": "(protected)/_dashboard/questionnaire/index.tsx",
      "parent": "/(protected)/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
